### ISSUE TITLE
Cross Origin Policy

### ISSUE THREAD

**Issue by Maarethyu** [Stuk/jszip-utils#10]
I have a Cross Origin Policy error when i try to get the content of an image, can you tell me how to bypass it ? I've searched everywhere and all the solutions don't work :/

**Comment by dduponchel** [comment]
Could you paste the full error message ?
If you're trying to get a resource on an other server, your browser will block the request [unless the second server says otherwise](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). The server needs to add a `Access-Control-Allow-Origin` HTTP header to do that.

**Comment by leizard** [comment]
that s exactly what I'm dealing with. Where could I put a Access-Control-Allow-Origin HTTP header. Could I put it  in the JSZipUtils when creating XMLHttpRequest ?

**Comment by eldyvoon** [comment]
I have this issue too, please fix this, I'm stuck now, couldn't download image on s3.

**Comment by eldyvoon** [comment]
I figured it out. I did it by using 

> crossorigin.me

. Initially I thought it was my s3's bucket config but eventually realised there's limitation of jszip-utils, but i manage to get it working but simple doing `crossorigin.me/http://..my_s3_image_path`

**Comment by anorman728** [comment]
Yeah, it's been months since the last comment, but I'm getting the problem, too... I can't get JSZip to work at all at the moment.

The crossorigin.me solution doesn't seem to work for me.

**Comment by victornpb** [comment]
@eldyvoon It is indeed the configuration of your s3 bucket. You need to configure the Access-Control-Allow-Origin to *

**Comment by bcastano02** [comment]
I am do using the API of the S3 for Java for I can have the fileStream.
